apiVersion: v1
kind: ConfigMap
metadata:
  name: budget-app-config
  namespace: budget-app
data:
  ALLOWED_ORIGINS: '["http://localhost:3000","http://localhost:8080","https://budget.jesseinit.dev"]'
  GOOGLE_REDIRECT_URI: "https://budget.jesseinit.dev/auth/google/callback"
