apiVersion: v1
kind: ConfigMap
metadata:
  name: budget-app-config-backend
  namespace: budget-app
data:
  ALLOWED_ORIGINS: '["https://budget.jesseinit.dev"]'
  GOOGLE_REDIRECT_URI: "https://budget.jesseinit.dev/auth/callback"
