---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-secret
  namespace: budget-app
spec:
  encryptedData:
    .dockerconfigjson: AgCez9ZCjOlK8dLHdyi4F5qOUpVp3O9RJn5eVPOvLTc4CcoaJrbk2adSjpoXqV3v8Cyz/bIYg/Y0sG9v5oKk+sr8iJV/YI6De3EhorkXAa+PatWPX9Q28rryP9wCBlrfo2A18l8AuCWVCdMhXAN16NA8f2qEC+WivwT9VaZwaleuzPHUsr1oqweuaB3VkkV1TFo5Qv28+ckwGQWCDh29yiWEyiYD3hIS0kIPLW5mDPbb0GHR/uU6NKlGAdtDyOW4im7sO7rHhnvR15dU6J+RVOBCVjEDB43mrUAD2/d/ZNIa9Qv8eF2EPPfUZnJMjO1vjcz/RAQtJKL/sUJ3M+A7mMA+yGHfJH+M+GugzZ705tib8V8NwvaoLXA/DLq4Z5YwMAjts1u33qWWI/i5Y+9kCmP20d0gkIpIu/CUjIxApk0THlg0lCjIFL/RRvtfcRyOae9IpEgd76rGb3EWqpaDoqFkZQg/WFocg+2ywZEQbsQlGmKZP27SwhaspQHJmTZIvOQmMfb/rDe5Jsvpk45196SmaYSeHi5zMnAf6UpGA1BEdvjUMJUIaU0yZzh9kdNiSU+TuWeqU1UTi+MpwvCLE0h2bpLeLnXdurq5lYJIvmEORea7Z57sg49dqp4icPllG2oHUxutzD9OSP6Qm1u7Ak5PZ1Qj9i/fxvkVYIjLriWlWZ7+SbHZ9VKaQOJLh51caB3C+d+pZkZgA/s+9KdB+y+MUKe+659rOzMAexvYBStnzlObB0iU1Mk2KkswQlsmT0lsbF1nhttpPC7n/RNpm4S/jYoxjhUk8gwz5FVQO9n6jXjlq1wLC8bZ3wYYVcAcd4RiBFHeqQ==
  template:
    metadata:
      name: ghcr-secret
      namespace: budget-app
    type: kubernetes.io/dockerconfigjson
